### ISSUE TITLE
demo 编译error

### ISSUE THREAD

**Issue by ghost** [sinofool/alipay-java-sdk#4]
@sinofool 

DemoAlipayGenericConfig.java:19: error: missing return value
DemoAlipayWapConfig.java:9: error: missing return value

**Comment by sinofool** [comment]
当然，我不能把PrivateKey写到代码里面。
支付宝没有提供测试环境，所有的账号都是正式的，你只能用自己的账号测试。

把测试Demo留作不能编译，比留个空白不能使用好。
